language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

install:
  - composer install

script:
  - composer grumphp

after_success:
  - composer scrutinizer